Data Analysis

In [114]:
import pandas as pd

In [115]:
lst = [10, 20, 30]
s = pd.Series([10,20,30])
s

0    10
1    20
2    30
dtype: int64

In [116]:
s*10

0    100
1    200
2    300
dtype: int64

In [117]:
type(s)

pandas.core.series.Series

In [118]:
s

0    10
1    20
2    30
dtype: int64

In [119]:
pd.Series([10, 20, 30], index = ["a", "b", "c"])

a    10
b    20
c    30
dtype: int64

In [120]:
pd.Series({"a": 1, "b": 200})

a      1
b    200
dtype: int64

In [121]:
# Series Properties
s.values

array([10, 20, 30])

In [122]:
s.index

RangeIndex(start=0, stop=3, step=1)

In [123]:
s.size

3

In [124]:
s.dtype

dtype('int64')

In [125]:
# Series operation
s.mean()

np.float64(20.0)

In [126]:
s.max()

np.int64(30)

In [127]:
s.min()

np.int64(10)

In [128]:
s.std()

np.float64(10.0)

In [129]:
s.sum()

np.int64(60)

In [130]:
s.value_counts()

10    1
20    1
30    1
Name: count, dtype: int64

In [131]:
a = pd.DataFrame([1,2],[3,4])
a

   0
3  1
4  2

In [132]:
type(a)

pandas.core.frame.DataFrame

In [133]:
pd.DataFrame({"A":[1,2], "B":[3,4]})

   A  B
0  1  3
1  2  4

In [134]:
# Load Data
df = pd.read_csv('WineQT.csv')

In [135]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,1
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,2
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,3
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,4

In [136]:
df.head(3)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,1
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,2

In [137]:
df.head(-1122)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,1
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,2
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,3
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,4
5,7.4,0.660,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,5,5
6,7.9,0.600,0.06,1.6,0.069,15.0,59.0,0.9964,3.30,0.46,9.4,5,6
7,7.3,0.650,0.00,1.2,0.065,15.0,21.0,0.9946,3.39,0.47,10.0,7,7
8,7.8,0.580,0.02,2.0,0.073,9.0,18.0,0.9968,3.36,0.57,9.5,7,8
9,6.7,0.580,0.08,1.8,0.097,15.0,65.0,0.9959,3.28,0.54,9.2,5,10
10,5.6,0.615,0.00,1.6,0.089,16.0,59.0,0.9943,3.58,0.52,9.9,5,12
11,7.8,0.610,0.29,1.6,0.114,9.0,29.0,0.9974,3.26,1.56,9.1,5,13
12,8.5,0.280,0.56,1.8,0.092,35.0,103.0,0.9969,3.30,0.75,10.5,7,16
13,7.9,0.320,0.51,1.8,0.341,17.0,56.0,0.9969,3.04,1.08,9.2,6,19
14,7.6,0.390,0.31,2.3,0.082,23.0,71.0,0.9982,3.52,0.65,9.7,5,21
15,7.9,0.430,0.21,1.6,0.106,10.0,37.0,0.9966,3.17,0.91,9.5,5,22
16,8.5,0.490,0.11,2.3,0.084,9.0,67.0,0.9968,3.17,0.53,9.4,5,23
17,6.9,0.400,0.14,2.4,0.085,21.0,40.0,0.9968,3.43,0.63,9.7,6,24
18,6.3,0.390,0.16,1.4,0.080,11.0,23.0,0.9955,3.34,0.56,9.3,5,25
19,7.6,0.410,0.24,1.8,0.080,4.0,11.0,0.9962,3.28,0.59,9.5,5,26
20,7.1,0.710,0.00,1.9,0.080,14.0,35.0,0.9972,3.47,0.55,9.4,5,28

In [138]:
df.tail()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,1592
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,1593
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,1594
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,1595
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,1597

In [139]:
df.tail(2)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,1595
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,1597

In [140]:
df.tail(-2)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,2
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,3
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,4
5,7.4,0.660,0.00,1.8,0.075,13.0,40.0,0.99780,3.51,0.56,9.4,5,5
6,7.9,0.600,0.06,1.6,0.069,15.0,59.0,0.99640,3.30,0.46,9.4,5,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,1592
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,1593
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,1594
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,1595
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,1597

In [141]:
df.sample(5)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
202,9.9,0.59,0.07,3.4,0.102,32.0,71.0,1.00015,3.31,0.71,9.800000,5,284
1052,5.3,0.47,0.11,2.2,0.048,16.0,89.0,0.99182,3.54,0.88,13.566667,7,1475
667,10.2,0.44,0.58,4.1,0.092,11.0,24.0,0.99745,3.29,0.99,12.000000,7,946
896,10.4,0.43,0.50,2.3,0.068,13.0,19.0,0.99600,3.10,0.87,11.400000,6,1267
624,8.9,0.75,0.14,2.5,0.086,9.0,30.0,0.99824,3.34,0.64,10.500000,5,885

In [142]:
df.sample(3, ignore_index=True)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.2,0.66,0.03,2.3,0.078,16.0,86.0,0.99743,3.53,0.57,9.7,5,893
1,10.2,0.24,0.49,2.4,0.075,10.0,28.0,0.99780,3.14,0.61,10.4,5,572
2,8.2,0.32,0.42,2.3,0.098,3.0,9.0,0.99506,3.27,0.55,12.3,6,1023

In [143]:
df.ndim

2

In [144]:
df.shape

(1143, 13)

In [145]:
df.size

14859

In [146]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality', 'Id'],
      dtype='object')

In [147]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1143 entries, 0 to 1142
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1143 non-null   float64
 1   volatile acidity      1143 non-null   float64
 2   citric acid           1143 non-null   float64
 3   residual sugar        1143 non-null   float64
 4   chlorides             1143 non-null   float64
 5   free sulfur dioxide   1143 non-null   float64
 6   total sulfur dioxide  1143 non-null   float64
 7   density               1143 non-null   float64
 8   pH                    1143 non-null   float64
 9   sulphates             1143 non-null   float64
 10  alcohol               1143 non-null   float64
 11  quality               1143 non-null   int64
 12  Id                    1143 non-null   int64
dtypes: float64(11), int64(2)
memory usage: 116.2 KB

In [148]:
df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
count,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000
mean,8.311111,0.531339,0.268364,2.532152,0.086933,15.615486,45.914698,0.996730,3.311015,0.657708,10.442111,5.657043,804.969379
std,1.747595,0.179633,0.196686,1.355917,0.047267,10.250486,32.782130,0.001925,0.156664,0.170399,1.082196,0.805824,463.997116
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000,0.000000
25%,7.100000,0.392500,0.090000,1.900000,0.070000,7.000000,21.000000,0.995570,3.205000,0.550000,9.500000,5.000000,411.000000
50%,7.900000,0.520000,0.250000,2.200000,0.079000,13.000000,37.000000,0.996680,3.310000,0.620000,10.200000,6.000000,794.000000
75%,9.100000,0.640000,0.420000,2.600000,0.090000,21.000000,61.000000,0.997845,3.400000,0.730000,11.100000,6.000000,1209.500000
max,15.900000,1.580000,1.000000,15.500000,0.611000,68.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000,1597.000000

In [149]:
df.describe(include='float')

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
count,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000
mean,8.311111,0.531339,0.268364,2.532152,0.086933,15.615486,45.914698,0.996730,3.311015,0.657708,10.442111
std,1.747595,0.179633,0.196686,1.355917,0.047267,10.250486,32.782130,0.001925,0.156664,0.170399,1.082196
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000
25%,7.100000,0.392500,0.090000,1.900000,0.070000,7.000000,21.000000,0.995570,3.205000,0.550000,9.500000
50%,7.900000,0.520000,0.250000,2.200000,0.079000,13.000000,37.000000,0.996680,3.310000,0.620000,10.200000
75%,9.100000,0.640000,0.420000,2.600000,0.090000,21.000000,61.000000,0.997845,3.400000,0.730000,11.100000
max,15.900000,1.580000,1.000000,15.500000,0.611000,68.000000,289.000000,1.003690,4.010000,2.000000,14.900000

In [150]:
df.describe(include='int')

           quality           Id
count  1143.000000  1143.000000
mean      5.657043   804.969379
std       0.805824   463.997116
min       3.000000     0.000000
25%       5.000000   411.000000
50%       6.000000   794.000000
75%       6.000000  1209.500000
max       8.000000  1597.000000

In [151]:
# Data Type Handling

df.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
Id                        int64
dtype: object

In [152]:
df.alcohol.dtype

dtype('float64')

In [153]:
df['fixed acidity'].dtype

dtype('float64')

In [154]:
df.select_dtypes(include='int').columns

Index(['quality', 'Id'], dtype='object')

In [155]:
df.select_dtypes(exclude='int').columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol'],
      dtype='object')

In [156]:
df.iloc[0:2, 0:4]

   fixed acidity  volatile acidity  citric acid  residual sugar
0            7.4              0.70          0.0             1.9
1            7.8              0.88          0.0             2.6

In [157]:
df['fixed acidity'][0]

np.float64(7.4)

In [158]:
df.iat[0,0]

np.float64(7.4)

In [159]:
df.iat[2,1]

np.float64(0.76)

In [160]:
# Missing Values

df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
Id                      0
dtype: int64

In [161]:
df.notnull().sum()

fixed acidity           1143
volatile acidity        1143
citric acid             1143
residual sugar          1143
chlorides               1143
free sulfur dioxide     1143
total sulfur dioxide    1143
density                 1143
pH                      1143
sulphates               1143
alcohol                 1143
quality                 1143
Id                      1143
dtype: int64

In [162]:
df.dropna()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,1
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,2
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,3
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,1592
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,1593
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,1594
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,1595
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,1597

In [163]:
df.fillna(0)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,1
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,2
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,3
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,1592
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,1593
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,1594
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,1595
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,1597

In [164]:
df.fillna(df.mean())

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,1
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,2
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,3
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,1592
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,1593
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,1594
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,1595
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,1597

In [165]:
# Duplicated Data
df.duplicated().sum()

np.int64(0)

In [166]:
# df.drop_duplicates(inplace=True)
df = df.drop_duplicates()

In [167]:
# Sorting
df.sort_values(by='alcohol')

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
388,14.3,0.31,0.74,1.8,0.075,6.0,15.0,1.00080,2.86,0.79,8.4,6,544
368,10.4,0.61,0.49,2.1,0.200,5.0,16.0,0.99940,3.16,0.63,8.4,3,517
1023,10.0,0.38,0.38,1.6,0.169,27.0,90.0,0.99914,3.15,0.65,8.5,5,1436
263,7.9,0.24,0.40,1.6,0.056,11.0,25.0,0.99670,3.32,0.87,8.7,6,371
1051,9.9,0.50,0.50,13.8,0.205,48.0,82.0,1.00242,3.16,0.75,8.8,5,1474
...,...,...,...,...,...,...,...,...,...,...,...,...,...
589,4.9,0.42,0.00,2.1,0.048,16.0,42.0,0.99154,3.71,0.74,14.0,7,821
419,5.0,0.42,0.24,2.0,0.060,19.0,50.0,0.99170,3.72,0.74,14.0,8,588
98,5.2,0.34,0.00,1.8,0.050,27.0,63.0,0.99160,3.68,0.79,14.0,6,144
96,5.2,0.34,0.00,1.8,0.050,27.0,63.0,0.99160,3.68,0.79,14.0,6,142
462,15.9,0.36,0.65,7.5,0.096,22.0,71.0,0.99760,2.98,0.84,14.9,5,652

In [168]:
df.sample(5).sort_index()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
526,8.2,0.59,0.00,2.5,0.093,19.0,58.0,1.00020,3.50,0.65,9.3,6,737
609,9.3,0.36,0.39,1.5,0.080,41.0,55.0,0.99652,3.47,0.73,10.9,6,854
628,7.2,0.66,0.03,2.3,0.078,16.0,86.0,0.99743,3.53,0.57,9.7,5,891
697,7.1,0.34,0.28,2.0,0.082,31.0,68.0,0.99694,3.45,0.48,9.4,5,991
930,6.5,0.51,0.15,3.0,0.064,12.0,27.0,0.99290,3.33,0.59,12.8,6,1311

In [169]:
df.sample(7, ignore_index=True).sort_index(ascending=False)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
6,8.7,0.52,0.09,2.5,0.091,20.0,49.0,0.99760,3.34,0.86,10.6,7,290
5,10.1,0.65,0.37,5.1,0.110,11.0,65.0,1.00260,3.32,0.64,10.4,6,608
4,6.1,0.58,0.23,2.5,0.044,16.0,70.0,0.99352,3.46,0.65,12.5,6,1151
3,6.7,0.16,0.64,2.1,0.059,24.0,52.0,0.99494,3.34,0.71,11.2,6,1566
2,7.4,0.36,0.30,1.8,0.074,17.0,24.0,0.99419,3.24,0.70,11.4,8,1549
1,7.1,0.46,0.14,2.8,0.076,15.0,37.0,0.99624,3.36,0.49,10.7,5,827
0,7.0,0.51,0.09,2.1,0.062,4.0,9.0,0.99584,3.35,0.54,10.5,5,1022

In [170]:
df.sample(5).reset_index(drop=True)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,8.8,0.550,0.04,2.2,0.119,14.0,56.0,0.99620,3.21,0.60,10.9,6,121
1,9.9,0.490,0.58,3.5,0.094,9.0,43.0,1.00040,3.29,0.58,9.0,5,593
2,7.0,0.510,0.09,2.1,0.062,4.0,9.0,0.99584,3.35,0.54,10.5,5,1022
3,7.5,0.570,0.02,2.6,0.077,11.0,35.0,0.99557,3.36,0.62,10.8,6,1379
4,8.3,0.625,0.20,1.5,0.080,27.0,119.0,0.99720,3.16,1.12,9.1,4,79

In [171]:
df.corr()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
fixed acidity,1.000000,-0.250728,0.673157,0.171831,0.107889,-0.164831,-0.110628,0.681501,-0.685163,0.174592,-0.075055,0.121970,-0.275826
volatile acidity,-0.250728,1.000000,-0.544187,-0.005751,0.056336,-0.001962,0.077748,0.016512,0.221492,-0.276079,-0.203909,-0.407394,-0.007892
citric acid,0.673157,-0.544187,1.000000,0.175815,0.245312,-0.057589,0.036871,0.375243,-0.546339,0.331232,0.106250,0.240821,-0.139011
residual sugar,0.171831,-0.005751,0.175815,1.000000,0.070863,0.165339,0.190790,0.380147,-0.116959,0.017475,0.058421,0.022002,-0.046344
chlorides,0.107889,0.056336,0.245312,0.070863,1.000000,0.015280,0.048163,0.208901,-0.277759,0.374784,-0.229917,-0.124085,-0.088099
free sulfur dioxide,-0.164831,-0.001962,-0.057589,0.165339,0.015280,1.000000,0.661093,-0.054150,0.072804,0.034445,-0.047095,-0.063260,0.095268
total sulfur dioxide,-0.110628,0.077748,0.036871,0.190790,0.048163,0.661093,1.000000,0.050175,-0.059126,0.026894,-0.188165,-0.183339,-0.107389
density,0.681501,0.016512,0.375243,0.380147,0.208901,-0.054150,0.050175,1.000000,-0.352775,0.143139,-0.494727,-0.175208,-0.363926
pH,-0.685163,0.221492,-0.546339,-0.116959,-0.277759,0.072804,-0.059126,-0.352775,1.000000,-0.185499,0.225322,-0.052453,0.132904
sulphates,0.174592,-0.276079,0.331232,0.017475,0.374784,0.034445,0.026894,0.143139,-0.185499,1.000000,0.094421,0.257710,-0.103954
alcohol,-0.075055,-0.203909,0.106250,0.058421,-0.229917,-0.047095,-0.188165,-0.494727,0.225322,0.094421,1.000000,0.484866,0.238087
quality,0.121970,-0.407394,0.240821,0.022002,-0.124085,-0.063260,-0.183339,-0.175208,-0.052453,0.257710,0.484866,1.000000,0.069708
Id,-0.275826,-0.007892,-0.139011,-0.046344,-0.088099,0.095268,-0.107389,-0.363926,0.132904,-0.103954,0.238087,0.069708,1.000000

In [172]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,1
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,2
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,3
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,4

In [173]:
df["quality"].unique()

array([5, 6, 7, 4, 8, 3])

In [174]:
df["fixed acidity"].unique()

array([ 7.4,  7.8, 11.2,  7.9,  7.3,  6.7,  5.6,  8.5,  7.6,  6.9,  6.3,
        7.1,  8.3,  5.2,  8.1,  8.8,  7.5,  4.6,  7.7,  6.6,  8.6, 10.2,
        7. ,  7.2,  8. ,  6.8,  6.2,  9.3,  5. ,  8.4, 10.1,  9.4,  8.2,
        5.8,  9.2,  8.9,  6.4, 11.5,  9.6, 12.8,  9.7,  8.7, 12. , 15. ,
       10.8, 11.1, 10. , 12.5, 10.3, 11.4,  9.9, 11.6, 10.4, 13.3, 10.6,
        9. ,  9.8, 13.4, 11.9, 10.9, 13.8,  9.1, 13.5,  6.1, 10.5, 12.6,
       13.7,  9.5, 12.2, 12.3, 15.6,  5.3, 11.3, 13. ,  6.5, 10.7, 12.9,
       14.3, 12.4, 15.5, 12.7, 13.2, 15.9,  5.1, 11.8,  4.9,  5.9, 11.7,
        5.4,  5.7,  6. ])

In [175]:
df["quality"].nunique()

6

In [176]:
df["quality"].value_counts()

quality
5    483
6    462
7    143
4     33
8     16
3      6
Name: count, dtype: int64

In [177]:
df[df["quality"]>5]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,3
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.99460,3.39,0.47,10.0,7,7
8,7.8,0.58,0.02,2.0,0.073,9.0,18.0,0.99680,3.36,0.57,9.5,7,8
12,8.5,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,3.30,0.75,10.5,7,16
13,7.9,0.32,0.51,1.8,0.341,17.0,56.0,0.99690,3.04,1.08,9.2,6,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1136,6.3,0.55,0.15,1.8,0.077,26.0,35.0,0.99314,3.32,0.82,11.6,6,1590
1137,5.4,0.74,0.09,1.7,0.089,16.0,26.0,0.99402,3.67,0.56,11.6,6,1591
1138,6.3,0.51,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,1592
1139,6.8,0.62,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,1593
1141,5.9,0.55,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,1595

In [178]:
df.alcohol*=1.10
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,10.34,5,0
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,10.78,5,1
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,10.78,5,2
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,10.78,6,3
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,10.34,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,12.10,6,1592
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,10.45,6,1593
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,11.55,5,1594
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,12.32,6,1595
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,11.22,5,1597

In [179]:
def rating(quality):
    if quality>5:
        return "Good"
    else:
        return "Bad"

In [180]:
df["quality review"] = df["quality"].apply(rating)
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,quality review
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,10.34,5,0,Bad
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,10.78,5,1,Bad
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,10.78,5,2,Bad
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,10.78,6,3,Good
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,10.34,5,4,Bad

In [181]:
df.to_csv("Wine.csv", index=False)

In [182]:
df["quality_label"] = df["quality"].map({3: "Very Bad",
                                         4: "Bad",
                                         5: "Good",
                                         5: "Very Good",
                                         7: "Nice",
                                         8: "Excellent"})

df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,quality review,quality_label
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,10.34,5,0,Bad,Very Good
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,10.78,5,1,Bad,Very Good
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,10.78,5,2,Bad,Very Good
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,10.78,6,3,Good,NaN
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,10.34,5,4,Bad,Very Good

In [183]:
df["quality_label2"] = df["quality"].map({"Good": "Good2",
                                         "Very Good": "Very Good2"})
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,quality review,quality_label,quality_label2
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,10.34,5,0,Bad,Very Good,NaN
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,10.78,5,1,Bad,Very Good,NaN
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,10.78,5,2,Bad,Very Good,NaN
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,10.78,6,3,Good,NaN,NaN
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,10.34,5,4,Bad,Very Good,NaN

In [184]:
df["quality_replace"] = df["quality_label"].replace({"Good": "Good2",
                       "Very Good": "Very Good2"})
df.head(11)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,quality review,quality_label,quality_label2,quality_replace
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,10.34,5,0,Bad,Very Good,NaN,Very Good2
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,10.78,5,1,Bad,Very Good,NaN,Very Good2
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,10.78,5,2,Bad,Very Good,NaN,Very Good2
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,10.78,6,3,Good,NaN,NaN,NaN
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,10.34,5,4,Bad,Very Good,NaN,Very Good2
5,7.4,0.660,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,10.34,5,5,Bad,Very Good,NaN,Very Good2
6,7.9,0.600,0.06,1.6,0.069,15.0,59.0,0.9964,3.30,0.46,10.34,5,6,Bad,Very Good,NaN,Very Good2
7,7.3,0.650,0.00,1.2,0.065,15.0,21.0,0.9946,3.39,0.47,11.00,7,7,Good,Nice,NaN,Nice
8,7.8,0.580,0.02,2.0,0.073,9.0,18.0,0.9968,3.36,0.57,10.45,7,8,Good,Nice,NaN,Nice
9,6.7,0.580,0.08,1.8,0.097,15.0,65.0,0.9959,3.28,0.54,10.12,5,10,Bad,Very Good,NaN,Very Good2
10,5.6,0.615,0.00,1.6,0.089,16.0,59.0,0.9943,3.58,0.52,10.89,5,12,Bad,Very Good,NaN,Very Good2

In [185]:
df.rename(columns={'fixed acidity':'acidity'})
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,quality review,quality_label,quality_label2,quality_replace
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,10.34,5,0,Bad,Very Good,NaN,Very Good2
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,10.78,5,1,Bad,Very Good,NaN,Very Good2
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,10.78,5,2,Bad,Very Good,NaN,Very Good2
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,10.78,6,3,Good,NaN,NaN,NaN
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,10.34,5,4,Bad,Very Good,NaN,Very Good2

In [186]:
df1 = pd.read_csv("wine_data.csv")
df1.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,name,date
0,8.50,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,3.30,0.75,10.50,7,16,WineA,2023-01-10
1,8.00,0.59,0.16,1.8,0.065,3.0,16.0,0.99620,3.42,0.92,10.50,7,128,WineB,2023-02-15
2,9.60,0.32,0.47,1.4,0.056,9.0,24.0,0.99695,3.22,0.82,10.30,7,200,WineC,2023-03-20
3,12.80,0.30,0.74,2.6,0.095,9.0,28.0,0.99940,3.20,0.77,10.80,7,205,WineD,2023-04-25
4,9.91,0.45,0.49,2.8,0.053,21.9,60.5,0.99683,3.31,0.90,8.88,4,5,Weingut Syrah Reserve 575,2023-02-12

In [187]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         220 non-null    float64
 1   volatile acidity      220 non-null    float64
 2   citric acid           220 non-null    float64
 3   residual sugar        220 non-null    float64
 4   chlorides             220 non-null    float64
 5   free sulfur dioxide   220 non-null    float64
 6   total sulfur dioxide  220 non-null    float64
 7   density               220 non-null    float64
 8   pH                    220 non-null    float64
 9   sulphates             220 non-null    float64
 10  alcohol               220 non-null    float64
 11  quality               220 non-null    int64
 12  Id                    220 non-null    int64
 13  name                  220 non-null    object
 14  date                  220 non-null    object
dtypes: float64(11), int64(2), object(2)
memory usage: 25.9+ KB

In [188]:
df1.name.str.upper()

0                                WINEA
1                                WINEB
2                                WINEC
3                                WINED
4            WEINGUT SYRAH RESERVE 575
                    ...
215           BODEGA PINOT CLASSIC 513
216       CASTELLO MERLOT GRAND CRU 41
217    BODEGA CHARDONNAY GRAND CRU 257
218       CHATEAU CABERNET SPECIAL 857
219       BODEGA SAUVIGNON CLASSIC 591
Name: name, Length: 220, dtype: object

In [189]:
df1.name.str.lower()

0                                winea
1                                wineb
2                                winec
3                                wined
4            weingut syrah reserve 575
                    ...
215           bodega pinot classic 513
216       castello merlot grand cru 41
217    bodega chardonnay grand cru 257
218       chateau cabernet special 857
219       bodega sauvignon classic 591
Name: name, Length: 220, dtype: object

In [190]:
df1.name.str.capitalize()

0                                Winea
1                                Wineb
2                                Winec
3                                Wined
4            Weingut syrah reserve 575
                    ...
215           Bodega pinot classic 513
216       Castello merlot grand cru 41
217    Bodega chardonnay grand cru 257
218       Chateau cabernet special 857
219       Bodega sauvignon classic 591
Name: name, Length: 220, dtype: object

In [191]:
df1.name.str.title()

0                                Winea
1                                Wineb
2                                Winec
3                                Wined
4            Weingut Syrah Reserve 575
                    ...
215           Bodega Pinot Classic 513
216       Castello Merlot Grand Cru 41
217    Bodega Chardonnay Grand Cru 257
218       Chateau Cabernet Special 857
219       Bodega Sauvignon Classic 591
Name: name, Length: 220, dtype: object

In [192]:
df1.name.str.len()

0       5
1       5
2       5
3       5
4      25
       ..
215    24
216    28
217    31
218    28
219    28
Name: name, Length: 220, dtype: int64

In [193]:
df1[df1.name.str.contains('a')]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,name,date
4,9.91,0.45,0.49,2.8,0.053,21.9,60.5,0.99683,3.31,0.90,8.88,4,5,Weingut Syrah Reserve 575,2023-02-12
5,8.72,0.56,0.34,0.8,0.059,22.3,59.8,0.99571,3.35,0.79,9.79,4,6,Bodega Riesling Special 559,2024-05-09
6,9.54,0.61,0.41,3.1,0.064,23.5,51.8,0.99716,3.32,0.73,9.15,4,7,Domaine Pinot Grand Cru 285,2022-01-14
7,9.08,0.63,0.49,1.1,0.072,18.1,42.5,0.99795,3.20,0.81,8.88,3,8,Domaine Riesling Premium 349,2023-07-24
8,8.88,0.44,0.40,2.9,0.079,15.3,43.6,0.99742,3.42,0.79,10.84,5,9,Domaine Cabernet Classic 105,2022-07-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,10.62,0.38,0.41,3.0,0.072,24.8,55.7,0.99732,3.16,0.79,10.99,6,216,Bodega Pinot Classic 513,2024-10-08
216,10.21,0.17,0.60,2.5,0.059,13.7,21.2,0.99388,3.21,0.72,11.25,7,217,Castello Merlot Grand Cru 41,2024-06-03
217,11.29,0.36,0.46,2.8,0.082,26.6,40.2,0.99651,3.27,0.84,11.24,7,218,Bodega Chardonnay Grand Cru 257,2022-02-22
218,9.21,0.36,0.51,2.6,0.082,10.3,19.6,0.99854,3.20,0.70,11.09,6,219,Chateau Cabernet Special 857,2022-02-12
219,10.02,0.21,0.47,1.8,0.050,17.2,33.5,0.99676,3.04,0.70,11.37,7,220,Bodega Sauvignon Classic 591,2022-03-24

#### **Date And Time Operations**

In [194]:
df1.date.dtype

dtype('O')

In [195]:
df1["date"] = pd.to_datetime(df1.date)
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         220 non-null    float64
 1   volatile acidity      220 non-null    float64
 2   citric acid           220 non-null    float64
 3   residual sugar        220 non-null    float64
 4   chlorides             220 non-null    float64
 5   free sulfur dioxide   220 non-null    float64
 6   total sulfur dioxide  220 non-null    float64
 7   density               220 non-null    float64
 8   pH                    220 non-null    float64
 9   sulphates             220 non-null    float64
 10  alcohol               220 non-null    float64
 11  quality               220 non-null    int64
 12  Id                    220 non-null    int64
 13  name                  220 non-null    object
 14  date                  220 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(11), int64(2), object(1)
memory usage: 25.9+ KB

In [196]:
df1.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,name,date
0,8.50,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,3.30,0.75,10.50,7,16,WineA,2023-01-10
1,8.00,0.59,0.16,1.8,0.065,3.0,16.0,0.99620,3.42,0.92,10.50,7,128,WineB,2023-02-15
2,9.60,0.32,0.47,1.4,0.056,9.0,24.0,0.99695,3.22,0.82,10.30,7,200,WineC,2023-03-20
3,12.80,0.30,0.74,2.6,0.095,9.0,28.0,0.99940,3.20,0.77,10.80,7,205,WineD,2023-04-25
4,9.91,0.45,0.49,2.8,0.053,21.9,60.5,0.99683,3.31,0.90,8.88,4,5,Weingut Syrah Reserve 575,2023-02-12

In [197]:
df1["Year"] = df1.date.dt.year
df1.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,name,date,Year
0,8.50,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,3.30,0.75,10.50,7,16,WineA,2023-01-10,2023
1,8.00,0.59,0.16,1.8,0.065,3.0,16.0,0.99620,3.42,0.92,10.50,7,128,WineB,2023-02-15,2023
2,9.60,0.32,0.47,1.4,0.056,9.0,24.0,0.99695,3.22,0.82,10.30,7,200,WineC,2023-03-20,2023
3,12.80,0.30,0.74,2.6,0.095,9.0,28.0,0.99940,3.20,0.77,10.80,7,205,WineD,2023-04-25,2023
4,9.91,0.45,0.49,2.8,0.053,21.9,60.5,0.99683,3.31,0.90,8.88,4,5,Weingut Syrah Reserve 575,2023-02-12,2023

In [198]:
df1["Month"] = df1.date.dt.month
df1.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,name,date,Year,Month
0,8.50,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,3.30,0.75,10.50,7,16,WineA,2023-01-10,2023,1
1,8.00,0.59,0.16,1.8,0.065,3.0,16.0,0.99620,3.42,0.92,10.50,7,128,WineB,2023-02-15,2023,2
2,9.60,0.32,0.47,1.4,0.056,9.0,24.0,0.99695,3.22,0.82,10.30,7,200,WineC,2023-03-20,2023,3
3,12.80,0.30,0.74,2.6,0.095,9.0,28.0,0.99940,3.20,0.77,10.80,7,205,WineD,2023-04-25,2023,4
4,9.91,0.45,0.49,2.8,0.053,21.9,60.5,0.99683,3.31,0.90,8.88,4,5,Weingut Syrah Reserve 575,2023-02-12,2023,2

#### **Add New Data**

In [199]:
df1.loc[5]

fixed acidity                                  8.72
volatile acidity                               0.56
citric acid                                    0.34
residual sugar                                  0.8
chlorides                                     0.059
free sulfur dioxide                            22.3
total sulfur dioxide                           59.8
density                                     0.99571
pH                                             3.35
sulphates                                      0.79
alcohol                                        9.79
quality                                           4
Id                                                6
name                    Bodega Riesling Special 559
date                            2024-05-09 00:00:00
Year                                           2024
Month                                             5
Name: 5, dtype: object

In [200]:
df1.loc[len(df1)-1]

fixed acidity                                  10.02
volatile acidity                                0.21
citric acid                                     0.47
residual sugar                                   1.8
chlorides                                       0.05
free sulfur dioxide                             17.2
total sulfur dioxide                            33.5
density                                      0.99676
pH                                              3.04
sulphates                                        0.7
alcohol                                        11.37
quality                                            7
Id                                               220
name                    Bodega Sauvignon Classic 591
date                             2022-03-24 00:00:00
Year                                            2022
Month                                              3
Name: 219, dtype: object

In [203]:
df1.loc[len(df1)] = [10, 0.57, 0.70, 1.9, 0.07, 17.7, 33.9, 0.9968, 3.11, 0.9, 11.45, 9, 225, "WineY", "2023-01-12", "2023", "1"]

In [204]:
df1.shape

(221, 17)

#### **Delete Data**

In [207]:
df1.drop(index=4, inplace=True)

In [208]:
df1.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,name,date,Year,Month
0,8.50,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,3.30,0.75,10.50,7,16,WineA,2023-01-10 00:00:00,2023,1
1,8.00,0.59,0.16,1.8,0.065,3.0,16.0,0.99620,3.42,0.92,10.50,7,128,WineB,2023-02-15 00:00:00,2023,2
2,9.60,0.32,0.47,1.4,0.056,9.0,24.0,0.99695,3.22,0.82,10.30,7,200,WineC,2023-03-20 00:00:00,2023,3
3,12.80,0.30,0.74,2.6,0.095,9.0,28.0,0.99940,3.20,0.77,10.80,7,205,WineD,2023-04-25 00:00:00,2023,4
5,8.72,0.56,0.34,0.8,0.059,22.3,59.8,0.99571,3.35,0.79,9.79,4,6,Bodega Riesling Special 559,2024-05-09 00:00:00,2024,5

In [ ]:
df1.drop(index=[1,2,3,5], inplace=True)

In [211]:
df1.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,name,date,Year,Month
0,8.50,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,3.30,0.75,10.50,7,16,WineA,2023-01-10 00:00:00,2023,1
6,9.54,0.61,0.41,3.1,0.064,23.5,51.8,0.99716,3.32,0.73,9.15,4,7,Domaine Pinot Grand Cru 285,2022-01-14 00:00:00,2022,1
7,9.08,0.63,0.49,1.1,0.072,18.1,42.5,0.99795,3.20,0.81,8.88,3,8,Domaine Riesling Premium 349,2023-07-24 00:00:00,2023,7
8,8.88,0.44,0.40,2.9,0.079,15.3,43.6,0.99742,3.42,0.79,10.84,5,9,Domaine Cabernet Classic 105,2022-07-09 00:00:00,2022,7
9,9.31,0.55,0.29,2.4,0.078,18.5,39.4,0.99652,3.24,0.76,8.97,3,10,Castello Merlot Classic 868,2023-12-06 00:00:00,2023,12

In [212]:
df1.drop(columns="pH", inplace=True)
df1.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,sulphates,alcohol,quality,Id,name,date,Year,Month
0,8.50,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,0.75,10.50,7,16,WineA,2023-01-10 00:00:00,2023,1
6,9.54,0.61,0.41,3.1,0.064,23.5,51.8,0.99716,0.73,9.15,4,7,Domaine Pinot Grand Cru 285,2022-01-14 00:00:00,2022,1
7,9.08,0.63,0.49,1.1,0.072,18.1,42.5,0.99795,0.81,8.88,3,8,Domaine Riesling Premium 349,2023-07-24 00:00:00,2023,7
8,8.88,0.44,0.40,2.9,0.079,15.3,43.6,0.99742,0.79,10.84,5,9,Domaine Cabernet Classic 105,2022-07-09 00:00:00,2022,7
9,9.31,0.55,0.29,2.4,0.078,18.5,39.4,0.99652,0.76,8.97,3,10,Castello Merlot Classic 868,2023-12-06 00:00:00,2023,12

In [213]:
df1.drop(columns=["name", "date", "Year"], inplace=True)
df1.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,sulphates,alcohol,quality,Id,Month
0,8.50,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,0.75,10.50,7,16,1
6,9.54,0.61,0.41,3.1,0.064,23.5,51.8,0.99716,0.73,9.15,4,7,1
7,9.08,0.63,0.49,1.1,0.072,18.1,42.5,0.99795,0.81,8.88,3,8,7
8,8.88,0.44,0.40,2.9,0.079,15.3,43.6,0.99742,0.79,10.84,5,9,7
9,9.31,0.55,0.29,2.4,0.078,18.5,39.4,0.99652,0.76,8.97,3,10,12

#### **Create a new column**

In [214]:
df1["High_Alcohol"] = df1.alcohol >= 10
df1.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,sulphates,alcohol,quality,Id,Month,High_Alcohol
0,8.50,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,0.75,10.50,7,16,1,True
6,9.54,0.61,0.41,3.1,0.064,23.5,51.8,0.99716,0.73,9.15,4,7,1,False
7,9.08,0.63,0.49,1.1,0.072,18.1,42.5,0.99795,0.81,8.88,3,8,7,False
8,8.88,0.44,0.40,2.9,0.079,15.3,43.6,0.99742,0.79,10.84,5,9,7,True
9,9.31,0.55,0.29,2.4,0.078,18.5,39.4,0.99652,0.76,8.97,3,10,12,False

In [215]:
df1["wine_type"] = "Red Wine"
df1.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,sulphates,alcohol,quality,Id,Month,High_Alcohol,wine_type
0,8.50,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,0.75,10.50,7,16,1,True,Red Wine
6,9.54,0.61,0.41,3.1,0.064,23.5,51.8,0.99716,0.73,9.15,4,7,1,False,Red Wine
7,9.08,0.63,0.49,1.1,0.072,18.1,42.5,0.99795,0.81,8.88,3,8,7,False,Red Wine
8,8.88,0.44,0.40,2.9,0.079,15.3,43.6,0.99742,0.79,10.84,5,9,7,True,Red Wine
9,9.31,0.55,0.29,2.4,0.078,18.5,39.4,0.99652,0.76,8.97,3,10,12,False,Red Wine

#### **Merge And Concat**

In [217]:
data1 = {
    'Name':['A', 'B', 'C'],
    'age':[21, 45, 67],
    'salary':[10000, 20000, 30000]
}

data2 = {
    'Name':['A', 'BB', 'C'],
    'age':[21, 54, 67],
    'salary':[10000, 25000, 30000]
}

In [218]:
new_df1 = pd.DataFrame(data1)
new_df2 = pd.DataFrame(data2)

In [219]:
new_df1.head()

  Name  age  salary
0    A   21   10000
1    B   45   20000
2    C   67   30000

In [220]:
new_df2.head()

  Name  age  salary
0    A   21   10000
1   BB   54   25000
2    C   67   30000

In [221]:
pd.concat([new_df1, new_df2])

  Name  age  salary
0    A   21   10000
1    B   45   20000
2    C   67   30000
0    A   21   10000
1   BB   54   25000
2    C   67   30000

In [222]:
pd.concat([new_df1, new_df2], ignore_index=True)

  Name  age  salary
0    A   21   10000
1    B   45   20000
2    C   67   30000
3    A   21   10000
4   BB   54   25000
5    C   67   30000

In [ ]:
pd.concat([new_df1, new_df2], ignore_index=True, axis=1)

   0   1      2   3   4      5
0  A  21  10000   A  21  10000
1  B  45  20000  BB  54  25000
2  C  67  30000   C  67  30000

In [226]:
new_df = pd.concat([new_df1, new_df2], ignore_index=True, axis=0)
new_df.head(6)

  Name  age  salary
0    A   21   10000
1    B   45   20000
2    C   67   30000
3    A   21   10000
4   BB   54   25000
5    C   67   30000

In [228]:
new_df.drop_duplicates(inplace=True)
new_df.head()

  Name  age  salary
0    A   21   10000
1    B   45   20000
2    C   67   30000
4   BB   54   25000

#### **Merge**

In [230]:
new_df1.head()

  Name  age  salary
0    A   21   10000
1    B   45   20000
2    C   67   30000

In [231]:
new_df2.head()

  Name  age  salary
0    A   21   10000
1   BB   54   25000
2    C   67   30000

In [234]:
pd.merge(new_df1, new_df2, on='age', how="outer")

  Name_x  age  salary_x Name_y  salary_y
0      A   21   10000.0      A   10000.0
1      B   45   20000.0    NaN       NaN
2    NaN   54       NaN     BB   25000.0
3      C   67   30000.0      C   30000.0